# Generated by Django 3.2.4 on 2021-06-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelfapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
